-- DMS 가 쓴다 — 테마/월페이퍼가 바뀔 때마다 matugen 이 이 파일을 통째로 다시
-- 쓴다(보더, 그룹바 색). 손으로 고쳐도 다음 테마 변경에 날아간다.
--
-- 레포가 빈 파일로 심는 건 셸이 처음 뜨기 전에도 hyprland.lua 의 require 가
-- 뭔가를 찾게 하기 위해서다. 색을 직접 잡고 싶으면 hyprland.lua 의 require
-- 목록에서 "colors" 를 빼고 general.col 을 거기 적는다.
