-- hyprland 설정 — 손으로 고치는 파일이다. 생성물이 아니다.
--
-- 살아있는 사본은 ~/.config/hypr/hyprland.lua 이고 평범한 쓰기 가능 파일이다.
-- 저장하면 하이프랜드가 바로 리로드하고, 문법이 깨진 편집은 에러만 찍고 직전
-- 설정이 계속 돈다. 그러니 저기서 굴리고, 레포 쪽은 시드 겸 백업으로 둔다
-- (../default.nix 의 활성화 스크립트가 파일이 *없을 때만* 복사한다).
--
-- ── 왜 .conf 가 아니라 .lua 인가 ────────────────────────────────────────────
-- 0.55 부터 hyprlang 이 deprecated 이고 설정은 Lua 다. 인터넷에 널린
-- hyprland.conf 예제는 그대로 안 붙는다 — `hyprconf2lua` 로 변환하거나 아래
-- 문법을 따라 쓴다. 값 이름 자체는 그대로라, 위키의 변수표는 여전히 유효하다.
--
-- ── 니리와의 관계 ──────────────────────────────────────────────────────────
-- 키 배치는 ../../niri/rice/config.kdl 에서 그대로 옮겼다. 두 세션을 오가며 쓸
-- 거라 근육기억이 갈리는 게 제일 큰 비용이기 때문이다. 레이아웃도 같은 이유로
-- dwindle 이 아니라 `scrolling` 이다 — 무한 띠 위에 컬럼이 쌓이는, 니리와 같은
-- 모델이다. 다만 1:1 은 아니고, 다른 곳마다 주석을 달아 뒀다.

-- 이 파일은 하이프랜드가 자동 생성한 게 아니다. 안 적으면 첫 실행에 "설정을
-- 만들어 줬다"는 안내가 뜬다.
hl.config({ autogenerated = false })


---------------
---- 입력 ----
---------------

-- 키 리맵(한/영, Caps 레이어)은 여기 없다. keyd 가 evdev 레벨에서 처리하므로
-- 컴포지터가 뭐든 똑같이 먹는다 — ../../keyboard.nix 참고.
hl.config({
    input = {
        kb_layout = "us",

        -- 니리의 focus-follows-mouse.
        follow_mouse = 1,

        touchpad = {
            natural_scroll = true,
            tap_to_click = true,
            disable_while_typing = true, -- 니리의 dwt
        },
    },
})

-- 세 손가락 가로 스와이프로 워크스페이스 전환.
hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })


-------------------
---- 모양/배치 ----
-------------------

hl.config({
    general = {
        gaps_in = 4,
        gaps_out = 8,
        border_size = 2,

        -- 니리와 같은 모델. dwindle 로 돌리려면 이 한 줄만 바꾸면 되고,
        -- 아래 "컬럼" 키바인드들이 함께 의미를 잃는다.
        layout = "scrolling",
    },

    decoration = {
        rounding = 12,
        active_opacity = 1.0,
        inactive_opacity = 1.0,
    },

    misc = {
        -- DMS 가 벽지를 깐다. 하이프랜드 기본 배경은 그 밑에서 한 번 번쩍일
        -- 뿐이라 꺼 둔다.
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        force_default_wallpaper = 0,
    },
})

-- 스크롤링 레이아웃. 값은 니리 config.kdl 의 layout 블록에서 옮겨왔다.
hl.config({
    scrolling = {
        column_width = 0.5,                            -- default-column-width
        explicit_column_widths = "0.333, 0.5, 0.667",  -- preset-column-widths
        -- 1 = 포커스한 컬럼을 최소한으로만 끌어와 화면에 넣는다(니리의 기본
        -- 동작). 0 이면 매번 가운데로 끌어온다 — 그건 Mod+C 로 따로 준다.
        focus_fit_method = 1,
    },
})

-- DMS 의 레이어(바, 스포트라이트, 알림)에는 애니메이션을 걸지 않는다. 셸이
-- 자기 안에서 이미 애니메이션을 하고 있어서 두 번 겹친다.
hl.layer_rule({ name = "dms-no-anim", match = { namespace = "^dms:.*" }, no_anim = true })
hl.layer_rule({ name = "quickshell-no-anim", match = { namespace = "^(quickshell)$" }, no_anim = true })


-------------------
---- 환경 변수 ----
-------------------

-- 여기서 세운 값은 *하이프랜드가 띄우는 자식 프로세스*에만 간다. DMS 는 uwsm 이
-- 만든 systemd 유닛으로 뜨므로 이 값들을 못 본다 — 셸까지 닿아야 하는 변수는
-- ~/.config/uwsm/env 나 NixOS 의 environment.sessionVariables 로 가야 한다.
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("QT_QPA_PLATFORM", "wayland")


-------------------
---- 키바인드 ----
-------------------

-- DMS 도 자기 기본 키바인드 묶음(dms/binds.lua)을 깔아 두지만 여기서는 안
-- 읽는다. **하이프랜드는 같은 키에 걸린 바인드를 위에서부터 전부 실행한다** —
-- 니리처럼 나중 것이 앞 것을 덮지 않는다. 그래서 겹치는 키(Mod+F, Mod+Q...)가
-- 토글을 두 번 때려 아무 일도 안 일어나는 꼴이 된다. 필요한 IPC 호출은 아래에
-- 직접 적었고, 셸이 만드는 치트시트(Mod+Shift+/)는 이 파일을 읽으므로 목록은
-- 그대로 나온다.
local mod = "SUPER"

-- 프로그램
hl.bind(mod .. " + Return", hl.dsp.exec_cmd("ghostty"))
-- 셸이 안 뜬 상태(베타 업데이트, 잘못된 설정)에서도 터미널을 열 수 있는 길.
-- 니리 쪽과 같은 이유로 남겨 둔 폴백 런처다.
hl.bind(mod .. " + D", hl.dsp.exec_cmd("fuzzel"))

-- DMS
hl.bind(mod .. " + space", hl.dsp.exec_cmd("dms ipc call spotlight toggle"))
hl.bind(mod .. " + V", hl.dsp.exec_cmd("dms ipc call clipboard toggle"))
hl.bind(mod .. " + N", hl.dsp.exec_cmd("dms ipc call notifications toggle"))
hl.bind(mod .. " + S", hl.dsp.exec_cmd("dms ipc call control-center toggle"))
hl.bind(mod .. " + comma", hl.dsp.exec_cmd("dms ipc call settings toggle"))
hl.bind(mod .. " + Escape", hl.dsp.exec_cmd("dms ipc call powermenu toggle"))
hl.bind(mod .. " + L", hl.dsp.exec_cmd("dms ipc call lock lock"))
hl.bind(mod .. " + SHIFT + slash", hl.dsp.exec_cmd("dms ipc call keybinds toggle hyprland"))
-- 니리엔 없던 것. 셸이 하이프랜드에서만 주는 오버뷰다.
hl.bind(mod .. " + O", hl.dsp.exec_cmd("dms ipc call hypr toggleOverview"))

-- 창
hl.bind(mod .. " + Q", hl.dsp.window.close())
hl.bind(mod .. " + F", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))
hl.bind(mod .. " + SHIFT + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(mod .. " + SHIFT + space", hl.dsp.window.float({ action = "toggle" }))
-- 로그아웃. **hl.dsp.exit() 이 아니다** — uwsm 세션에서 컴포지터를 직접 죽이면
-- 클라이언트 밑에서 바닥을 빼는 꼴이라 유닛들이 어중간한 상태로 남는다.
hl.bind(mod .. " + SHIFT + E", hl.dsp.exec_cmd("uwsm stop"))

-- 포커스. 컬럼 사이는 layout 메시지("focus")로 간다 — 끝에서 감싸 돌고,
-- 옆 모니터로 새지 않는다. 컬럼 *안*의 위아래는 평범한 방향 포커스다.
hl.bind(mod .. " + H", hl.dsp.layout("focus l"))
hl.bind(mod .. " + left", hl.dsp.layout("focus l"))
hl.bind(mod .. " + right", hl.dsp.layout("focus r"))
-- 니리 설정에 Mod+L 로 오른쪽 가기가 없는 건 그 자리가 잠금이라서다. 여기서도
-- 그대로 둔다.
hl.bind(mod .. " + J", hl.dsp.focus({ direction = "d" }))
hl.bind(mod .. " + K", hl.dsp.focus({ direction = "u" }))
hl.bind(mod .. " + down", hl.dsp.focus({ direction = "d" }))
hl.bind(mod .. " + up", hl.dsp.focus({ direction = "u" }))
hl.bind(mod .. " + Home", hl.dsp.focus({ window = "first" }))
hl.bind(mod .. " + End", hl.dsp.focus({ window = "last" }))
-- 니리의 center-column 자리. 정확히 같지는 않다 — 이건 활성 컬럼을 화면 안에
-- 완전히 넣는 것이고, 가운데 정렬은 위의 focus_fit_method 가 정한다.
hl.bind(mod .. " + C", hl.dsp.layout("fit_into_view"))

-- 이동
hl.bind(mod .. " + CTRL + H", hl.dsp.layout("swapcol l"))
hl.bind(mod .. " + CTRL + left", hl.dsp.layout("swapcol l"))
hl.bind(mod .. " + CTRL + right", hl.dsp.layout("swapcol r"))
hl.bind(mod .. " + CTRL + J", hl.dsp.window.move({ direction = "d" }))
hl.bind(mod .. " + CTRL + K", hl.dsp.window.move({ direction = "u" }))
hl.bind(mod .. " + CTRL + down", hl.dsp.window.move({ direction = "d" }))
hl.bind(mod .. " + CTRL + up", hl.dsp.window.move({ direction = "u" }))

-- 컬럼 폭
hl.bind(mod .. " + equal", hl.dsp.layout("colresize +0.1"))
hl.bind(mod .. " + minus", hl.dsp.layout("colresize -0.1"))
-- 니리의 switch-preset-column-width. 목록은 위 explicit_column_widths 다.
hl.bind(mod .. " + R", hl.dsp.layout("colresize +conf"))

-- 워크스페이스. 니리는 세로로 쌓이고 하이프랜드는 번호가 붙을 뿐, U/I 가
-- 아래/위라는 감각은 같다.
hl.bind(mod .. " + U", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mod .. " + I", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mod .. " + CTRL + U", hl.dsp.window.move({ workspace = "e+1" }))
hl.bind(mod .. " + CTRL + I", hl.dsp.window.move({ workspace = "e-1" }))
for i = 1, 5 do
    hl.bind(mod .. " + " .. i, hl.dsp.focus({ workspace = i }))
end

-- 마우스. 니리엔 없지만 하이프랜드에선 관용이고, 띄운 창을 다룰 때 편하다.
hl.bind(mod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- 스크린샷. 니리는 컴포지터가 직접 찍지만 하이프랜드는 아니라서 hyprshot 을
-- 쓴다(../default.nix 가 깐다). 저장 위치는 니리의 screenshot-path 와 맞췄다.
local shot = "hyprshot --silent --output-folder ~/Pictures/Screenshots -m "
hl.bind("Print", hl.dsp.exec_cmd(shot .. "region"))
hl.bind("CTRL + Print", hl.dsp.exec_cmd(shot .. "output"))
hl.bind("ALT + Print", hl.dsp.exec_cmd(shot .. "window"))

-- 미디어/밝기. locked=true 는 잠금 화면에서도 먹으라는 뜻이다(니리의
-- allow-when-locked), repeating=true 는 누르고 있으면 반복.
local mediakey = { locked = true, repeating = true }
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("dms ipc call audio increment 5"), mediakey)
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("dms ipc call audio decrement 5"), mediakey)
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("dms ipc call audio mute"), { locked = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("dms ipc call mic mute"), { locked = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("dms ipc call brightness increment 5"), mediakey)
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("dms ipc call brightness decrement 5"), mediakey)

-- 리싱 스크립트. exec_cmd 는 sh -c 를 거치므로 $HOME 이 풀린다.
-- 프로필 전환은 두 세션이 반씩 나눠 갖는다 — 니리 조각(profile.kdl)은 여기서
-- 아무 일도 안 하고, DMS 조각(색·투명도·둥글기)은 그대로 적용된다.
hl.bind(mod .. " + SHIFT + P", hl.dsp.exec_cmd("$HOME/nixos-config/apps/rice-switch --next"))
hl.bind(mod .. " + SHIFT + W", hl.dsp.exec_cmd("$HOME/nixos-config/apps/rice-wall"))
hl.bind(mod .. " + CTRL + W", hl.dsp.exec_cmd("$HOME/nixos-config/apps/rice-wall --pick"))
hl.bind(mod .. " + ALT + W", hl.dsp.exec_cmd("$HOME/nixos-config/apps/rice-wall --yazi"))


-------------------
---- DMS 조각 ----
-------------------

-- 셸이 설정 GUI 와 matugen 으로 써 넣는 파일들. 색·커서·모니터·창 규칙이 여기서
-- 온다. 마지막에 부르므로 겹치는 값(gaps, rounding)은 DMS 쪽이 이긴다 — 레포
-- 값으로 되돌리고 싶으면 그 줄을 빼면 된다.
--
-- pcall 인 건 니리 include 의 `optional=true` 와 같은 뜻이다. 파일 하나가
-- 없다고 설정 전체가 죽으면 세션이 통째로 하이프랜드 기본값으로 떨어진다.
--
-- binds-user 는 DMS 설정 GUI 가 키를 추가할 때 쓰는 자리다(기본은 빈 파일).
-- 위에서 이미 잡은 키를 거기서 또 잡으면 둘 다 실행되니, 그럴 땐 그 파일에서
-- hl.unbind() 를 먼저 부른다.
for _, fragment in ipairs({ "colors", "cursor", "outputs", "windowrules", "layout", "binds-user" }) do
    pcall(require, "dms." .. fragment)
end
