-- hyprland 설정 — 손으로 고치는 파일이다. 생성물이 아니다.
--
-- 살아있는 사본은 ~/.config/hypr/hyprland.lua 이고 평범한 쓰기 가능 파일이다.
-- 저장하면 하이프랜드가 바로 리로드하고, 문법이 깨진 편집은 에러만 찍고 직전
-- 설정이 계속 돈다. 그러니 저기서 굴리고, 레포 쪽은 시드 겸 백업으로 둔다
-- (../default.nix 의 활성화 스크립트가 파일이 *없을 때만* 복사한다).
--
-- ── 왜 .conf 가 아니라 .lua 인가 ────────────────────────────────────────────
-- 0.55 부터 hyprlang 이 deprecated 이고 설정은 Lua 다. 인터넷에 널린
-- hyprland.conf 예제는 그대로 안 붙는다 — `hyprconf2lua` 로 변환하거나 아래
-- 문법을 따라 쓴다. 값 이름 자체는 그대로라, 위키의 변수표는 여전히 유효하다.
--
-- ── 니리와의 관계 ──────────────────────────────────────────────────────────
-- 키 배치는 ../../niri/rice/config.kdl 에서 그대로 옮겼다. 두 세션을 오가며 쓸
-- 거라 근육기억이 갈리는 게 제일 큰 비용이기 때문이다. 레이아웃도 같은 이유로
-- dwindle 이 아니라 `scrolling` 이다 — 무한 띠 위에 컬럼이 쌓이는, 니리와 같은
-- 모델이다. 다만 1:1 은 아니고, 다른 곳마다 주석을 달아 뒀다.

-- 이 파일은 하이프랜드가 자동 생성한 게 아니다. 안 적으면 첫 실행에 "설정을
-- 만들어 줬다"는 안내가 뜬다.
hl.config({ autogenerated = false })


---------------
---- 입력 ----
---------------

-- 키 리맵(한/영, Caps 레이어)은 여기 없다. keyd 가 evdev 레벨에서 처리하므로
-- 컴포지터가 뭐든 똑같이 먹는다 — ../../keyboard.nix 참고.
hl.config({
    input = {
        kb_layout = "us",

        -- 클릭해야 포커스가 간다. 세 WM 모두 같게 뒀다(니리는
        -- focus-follows-mouse 줄을 뺐고, rift 는 focus_follows_mouse = false).
        --
        -- 호버 포커스와 키보드 타일러는 누가 주도권을 갖는지에 대해 서로 다른
        -- 답을 갖고 있다. 포인터는 마지막으로 놓아둔 자리에 그대로 있으면서도
        -- 포커스에 대한 권리를 계속 주장한다 — 키보드로 옮겨 간 창에 타이핑을
        -- 시작하면 첫 타가 커서가 얹혀 있던 엉뚱한 창으로 들어갈 수 있고,
        -- 배경 창 위에서 스크롤하면 포커스를 통째로 빼앗긴다.
        --
        -- 반대 방향(키보드로 포커스를 옮기면 커서가 따라오는 것)은 rift 쪽에서
        -- 켜 두었다. 하이프랜드에 같은 설정은 없다.
        follow_mouse = 0,

        touchpad = {
            natural_scroll = true,
            tap_to_click = true,
            disable_while_typing = true, -- 니리의 dwt
        },
    },
})

-- 휠 클릭을 누른 채 마우스를 움직이면 스크롤(libinput 의 on-button-down).
-- 누르고 움직이지 않은 채 떼면 휠 클릭은 그대로 나가되, 눌린 순간이 아니라 뗀
-- 순간에 나간다 — libinput 이 스크롤이냐 클릭이냐를 릴리즈까지 유보하기 때문
-- 이다. 그 대가로 미들 드래그(패닝)는 전부 스크롤로 먹혀서 사라진다.
--
-- input 전역이 아니라 장치별로 거는 이유: input.scroll_method 는 터치패드에도
-- 걸리는데 input.touchpad 에는 이를 되돌릴 scroll_method 가 없다(0.56 스텁의
-- HL.ConfigOpt.Input.Touchpad 참고). 이 파일이 노트북에 심기는 순간 두 손가락
-- 스크롤이 조용히 죽는다. 마우스를 바꾸면 이름도 바꿔야 하고, 이름은
-- `hyprctl devices` 의 mice 절에 있다.
--
-- scroll_button_lock 은 켜지 않는다. 켜면 클릭 한 번이 스크롤 모드 토글이 되어
-- 휠 클릭 자체가 없어진다 — 이 설정으로 지키려던 것이 그것이다.
hl.device({
    name = "compx-2.4g-receiver-mouse",
    scroll_method = "on_button_down",
    scroll_button = 274, -- BTN_MIDDLE
})

-- 세 손가락 가로 스와이프로 워크스페이스 전환.
hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })


-------------------
---- 모양/배치 ----
-------------------

hl.config({
    general = {
        gaps_in = 4,
        gaps_out = 8,
        border_size = 2,

        -- 니리와 같은 모델. dwindle 로 돌리려면 이 한 줄만 바꾸면 되고,
        -- 아래 "컬럼" 키바인드들이 함께 의미를 잃는다.
        layout = "scrolling",
    },

    -- 투명도·흐리게·어둡게·그림자는 여기 없다. 손으로 정하는 값이 아니라 화면을
    -- 보면서 맞추는 값이라 apps/rice-decor 가 ~/.config/hypr/decor.lua 에 쓰고,
    -- 그 조각을 이 파일 맨 끝에서 부른다. 둥글기만 여기 남는데, 그것도 DMS 가
    -- 덮는다(맨 아래 조각 주석).
    decoration = {
        rounding = 12,
    },

    misc = {
        -- DMS 가 벽지를 깐다. 하이프랜드 기본 배경은 그 밑에서 한 번 번쩍일
        -- 뿐이라 꺼 둔다.
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        force_default_wallpaper = 0,
    },
})

-- 스크롤링 레이아웃. 값은 니리 config.kdl 의 layout 블록에서 옮겨왔다.
hl.config({
    scrolling = {
        column_width = 0.5,                            -- default-column-width
        explicit_column_widths = "0.333, 0.5, 0.667",  -- preset-column-widths
        -- 1 = 포커스한 컬럼을 최소한으로만 끌어와 화면에 넣는다(니리의 기본
        -- 동작). 0 이면 매번 가운데로 끌어온다 — 그건 Mod+C 로 따로 준다.
        focus_fit_method = 1,
    },
})

-- DMS 의 레이어(바, 스포트라이트, 알림)에는 애니메이션을 걸지 않는다. 셸이
-- 자기 안에서 이미 애니메이션을 하고 있어서 두 번 겹친다.
hl.layer_rule({ name = "dms-no-anim", match = { namespace = "^dms:.*" }, no_anim = true })
hl.layer_rule({ name = "quickshell-no-anim", match = { namespace = "^(quickshell)$" }, no_anim = true })


-------------------
---- 환경 변수 ----
-------------------

-- 여기서 세운 값은 *하이프랜드가 띄우는 자식 프로세스*에만 간다. DMS 는 uwsm 이
-- 만든 systemd 유닛으로 뜨므로 이 값들을 못 본다 — 셸까지 닿아야 하는 변수는
-- ~/.config/uwsm/env 나 NixOS 의 environment.sessionVariables 로 가야 한다.
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("QT_QPA_PLATFORM", "wayland")


-------------------
---- 키바인드 ----
-------------------

-- DMS 도 자기 기본 키바인드 묶음(dms/binds.lua)을 깔아 두지만 여기서는 안
-- 읽는다. **하이프랜드는 같은 키에 걸린 바인드를 위에서부터 전부 실행한다** —
-- 니리처럼 나중 것이 앞 것을 덮지 않는다. 그래서 겹치는 키(Mod+F, Mod+Q...)가
-- 토글을 두 번 때려 아무 일도 안 일어나는 꼴이 된다. 필요한 IPC 호출은 아래에
-- 직접 적었고, 셸이 만드는 치트시트(Mod+Shift+/)는 이 파일을 읽으므로 목록은
-- 그대로 나온다.
local mod = "SUPER"

-- 세 티어가 전부다. rift 와 니리도 같은 세 티어이고, macOS 만 mod 가 Alt 다
-- (Cmd 는 시스템이 가져간다). 전체 표는 docs/keymap.md.
--
--   Mod          간다, 연다
--   Mod + SHIFT  창을 데리고 간다
--   Mod + CTRL   모니터를 넘는다, WM 자신에게 말한다
--
-- 예전엔 이동이 Mod+CTRL 이었다. 그 자리를 SHIFT 로 옮긴 건 CTRL 티어를
-- 비우기 위해서다 — 모니터 이동을 넣을 자리가 없었다.

-- 프로그램
hl.bind(mod .. " + Return", hl.dsp.exec_cmd("ghostty"))
-- 셸이 안 뜬 상태(베타 업데이트, 잘못된 설정)에서도 터미널을 열 수 있는 길.
-- 니리 쪽과 같은 이유로 남겨 둔 폴백 런처다.
hl.bind(mod .. " + D", hl.dsp.exec_cmd("fuzzel"))

-- DMS
hl.bind(mod .. " + space", hl.dsp.exec_cmd("dms ipc call spotlight toggle"))
hl.bind(mod .. " + V", hl.dsp.exec_cmd("dms ipc call clipboard toggle"))
hl.bind(mod .. " + N", hl.dsp.exec_cmd("dms ipc call notifications toggle"))
hl.bind(mod .. " + S", hl.dsp.exec_cmd("dms ipc call control-center toggle"))
hl.bind(mod .. " + Escape", hl.dsp.exec_cmd("dms ipc call powermenu toggle"))
-- 치트시트. 셸이 이 파일을 읽어서 만든다. H 는 IJKL 이 왼쪽을 J 로 가져가면서
-- 통째로 빈 자리가 됐고, Help 로 읽힌다. rift 에는 대응물이 없다 —
-- 그쪽 치트시트는 docs/keymap.md 다.
hl.bind(mod .. " + H", hl.dsp.exec_cmd("dms ipc call keybinds toggle hyprland"))
-- 오버뷰. 예전엔 Mod+O 였는데 그 자리는 이제 워크스페이스 앞으로 가기다.
-- rift 는 같은 키에서 macOS 미션 컨트롤을 연다.
hl.bind(mod .. " + E", hl.dsp.exec_cmd("dms ipc call hypr toggleOverview"))
--
-- 버린 것 둘:
--   Mod+L      잠금. IJKL 이 오른쪽을 L 로 가져갔다. 잠금은 Mod+Escape 의
--              파워메뉴에 있고, 거기엔 잘못 눌렀을 때 되돌릴 기회까지 있다.
--   Mod+comma  DMS 설정 GUI. 런처에서 이름으로 부르면 된다. rift 는 이 자리를
--              toggle_stack 으로 쓴다.
--
-- Mod+SHIFT+E 는 로그아웃(`uwsm stop`)이었다. Mod+SHIFT+F / Mod+SHIFT+space 와
-- 손 모양이 겹쳐서 오타 한 번이면 세션이 통째로 날아가는 자리라 뺐다. 다시 걸 일이
-- 있으면 **hl.dsp.exit() 이 아니라** `uwsm stop` 이다 — uwsm 세션에서 컴포지터를
-- 직접 죽이면 클라이언트 밑에서 바닥을 빼는 꼴이라 유닛들이 어중간하게 남는다.

-- 창
hl.bind(mod .. " + Q", hl.dsp.window.close())
hl.bind(mod .. " + F", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))
hl.bind(mod .. " + SHIFT + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(mod .. " + SHIFT + space", hl.dsp.window.float({ action = "toggle" }))

------------------------------------------------------------------------
-- 티어 1 — Mod: 간다
------------------------------------------------------------------------
-- 방향은 IJKL, 화살표와 같은 역T자다:
--
--         I                 ↑
--    J    K    L        ←   ↓   →
--
-- hjkl 이 아니다. hjkl 은 한 줄에 늘어선 네 개일 뿐 모양이 없다 — vim 유산이지
-- 공간이 아니고, 창 관리는 공간 작업이다. 화살표는 어느 티어에서든 같은 동작에
-- 같이 걸려 있다. IJKL 이 흉내내는 대상이기도 하고, K 가 "위"에서 "아래"로
-- 뒤집힌 걸 손이 익히는 동안의 안전망이기도 하다.
--
-- 컬럼 사이(J/L)는 layout 메시지로 간다 — 끝에서 감싸 돌고, 옆 모니터로 새지
-- 않는다. 컬럼 *안*의 위아래(I/K)는 평범한 방향 포커스다.
hl.bind(mod .. " + J", hl.dsp.layout("focus l"))
hl.bind(mod .. " + L", hl.dsp.layout("focus r"))
hl.bind(mod .. " + left", hl.dsp.layout("focus l"))
hl.bind(mod .. " + right", hl.dsp.layout("focus r"))
hl.bind(mod .. " + I", hl.dsp.focus({ direction = "u" }))
hl.bind(mod .. " + K", hl.dsp.focus({ direction = "d" }))
hl.bind(mod .. " + up", hl.dsp.focus({ direction = "u" }))
hl.bind(mod .. " + down", hl.dsp.focus({ direction = "d" }))

-- 니리의 focus-column-first/last 를 Mod+Home/End 로 옮겨 뒀었지만 둘 다 죽은
-- 바인드였다. focus 의 `window` 는 위치 키워드가 아니라 창 셀렉터(class:, title:,
-- address:)라서 "first"/"last" 는 아무것도 못 찾고 경고만 찍는다. 스크롤링
-- 레이아웃에 끝 컬럼으로 뛰는 메시지도 없다 — layoutmsg("focus ...") 는 첫 글자만
-- 방향으로 읽어서 leftmost/rightmost/last 가 전부 l/r 과 똑같이 한 칸만 가고,
-- 그 한 칸은 끝에서 감싸 돌기까지 한다. 되살리려면 hl.get_windows() 로 컬럼을
-- 직접 훑는 함수를 써야 하고, 동작을 확인한 형태가 docs/hyprland-binds.md 에 있다.

-- 니리의 center-column 자리. 정확히 같지는 않다 — 이건 활성 컬럼을 화면 안에
-- 완전히 넣는 것이고, 가운데 정렬은 위의 focus_fit_method 가 정한다.
hl.bind(mod .. " + C", hl.dsp.layout("fit_into_view"))

-- 컬럼 폭
hl.bind(mod .. " + equal", hl.dsp.layout("colresize +0.1"))
hl.bind(mod .. " + minus", hl.dsp.layout("colresize -0.1"))
-- 니리의 switch-preset-column-width. 목록은 위 explicit_column_widths 다.
-- rift 에는 이 동작이 아예 없어서 그쪽은 같은 키에 monocle 스크립트가 걸린다.
hl.bind(mod .. " + R", hl.dsp.layout("colresize +conf"))

-- 워크스페이스. U 가 뒤로, O 가 앞으로 — I 를 위에서 감싸는 두 자리다.
-- 예전엔 U/I 였는데 IJKL 이 I 를 가져갔다. 니리·rift 도 같은 두 키다.
hl.bind(mod .. " + U", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mod .. " + O", hl.dsp.focus({ workspace = "e+1" }))
-- 직전 워크스페이스. 검증함 (2026-08-06, 0.56.1) — 2↔5↔7 왕복까지 봤다.
--
-- 철자는 `previous` 여야 한다. `prev` 는 `ok` 를 돌려주면서 아무 일도 안 하고,
-- `previous_per_monitor` 는 `Bad workspace` 다.
--
-- 세션에 직전 워크스페이스가 아직 없을 때도 `Bad workspace` 가 나온다. 문법이
-- 틀렸을 때와 메시지가 같으니, 이 한 줄로 확인할 거면 워크스페이스를 한 번
-- 옮겼다 온 뒤에 해야 한다:
--
--   hyprctl dispatch 'hl.dsp.focus({ workspace = 5 })'
--   hyprctl dispatch 'hl.dsp.focus({ workspace = "previous" })'
hl.bind(mod .. " + Tab", hl.dsp.focus({ workspace = "previous" }))
for i = 1, 9 do
    hl.bind(mod .. " + " .. i, hl.dsp.focus({ workspace = i }))
end

------------------------------------------------------------------------
-- 티어 2 — Mod+SHIFT: 창을 데리고 간다
------------------------------------------------------------------------
-- 규칙 하나가 네 묶음에 그대로 걸린다: 방향, 워크스페이스 앞뒤, 워크스페이스
-- 번호, 그리고 큰 형제가 있는 창 상태 두 개(위의 F/space).
hl.bind(mod .. " + SHIFT + J", hl.dsp.layout("swapcol l"))
hl.bind(mod .. " + SHIFT + L", hl.dsp.layout("swapcol r"))
hl.bind(mod .. " + SHIFT + left", hl.dsp.layout("swapcol l"))
hl.bind(mod .. " + SHIFT + right", hl.dsp.layout("swapcol r"))
hl.bind(mod .. " + SHIFT + I", hl.dsp.window.move({ direction = "u" }))
hl.bind(mod .. " + SHIFT + K", hl.dsp.window.move({ direction = "d" }))
hl.bind(mod .. " + SHIFT + up", hl.dsp.window.move({ direction = "u" }))
hl.bind(mod .. " + SHIFT + down", hl.dsp.window.move({ direction = "d" }))

hl.bind(mod .. " + SHIFT + U", hl.dsp.window.move({ workspace = "e-1" }))
hl.bind(mod .. " + SHIFT + O", hl.dsp.window.move({ workspace = "e+1" }))
-- 창을 워크스페이스 N 으로. rift 에만 있던 것이고, 여기 자리는 비어 있었다.
for i = 1, 9 do
    hl.bind(mod .. " + SHIFT + " .. i, hl.dsp.window.move({ workspace = i }))
end

------------------------------------------------------------------------
-- 티어 3 — Mod+CTRL: 모니터를 넘는다, WM 에게 말한다
------------------------------------------------------------------------
-- 검증함 (2026-08-06, 0.56.1, eDP-1 + DP-1 실기). `monitor` 는 방향 약자
-- l/r/u/d 와 full word(left/right/up/down)를 받고, 창이 실제로 넘어간다.
-- 이름·id·`current`·`+1`/`-1` 도 같이 받는다.
--
-- 옆에 모니터가 없는 방향은 `Invalid monitor / monitor doesn't exist` 다. 이게
-- 문법 오류처럼 보이는 게 함정이다 — 모니터가 하나뿐이면 네 방향이 전부 저
-- 메시지를 돌려주고, **겹쳐 배치된 모니터도 마찬가지다.** 헤드리스 출력을
-- 만들어 확인할 거면 위치부터 봐야 한다. `hyprctl output create headless` 는
-- 기존 모니터 안쪽에 얹히는 수가 있고, 그 배치에서는 어느 방향으로도 "옆"이
-- 아니다. `hyprctl keyword` 로는 못 옮긴다(lua 설정에서는 `eval` 뿐).
hl.bind(mod .. " + CTRL + J", hl.dsp.window.move({ monitor = "l" }))
hl.bind(mod .. " + CTRL + L", hl.dsp.window.move({ monitor = "r" }))
hl.bind(mod .. " + CTRL + I", hl.dsp.window.move({ monitor = "u" }))
hl.bind(mod .. " + CTRL + K", hl.dsp.window.move({ monitor = "d" }))
hl.bind(mod .. " + CTRL + left", hl.dsp.window.move({ monitor = "l" }))
hl.bind(mod .. " + CTRL + right", hl.dsp.window.move({ monitor = "r" }))
hl.bind(mod .. " + CTRL + up", hl.dsp.window.move({ monitor = "u" }))
hl.bind(mod .. " + CTRL + down", hl.dsp.window.move({ monitor = "d" }))

-- 이웃과 합치기 / 떼기. rift 의 Mod+Ctrl+E(consume_or_expel_window)와 니리의
-- consume-or-expel-window-right 자리다. 세 WM 에서 같은 키가 같은 일을 한다.
--
-- 하이프랜드에는 그 하나짜리 액션이 없다. layoutmsg 로 쪼개져 있고, 둘 중 뭘
-- 부를지는 지금 상태를 보고 여기서 정해야 한다:
--
--   consume   다음 컬럼의 맨 위 창 하나를 이 컬럼으로 끌어온다
--   promote   활성 창을 컬럼에서 빼내 바로 오른쪽에 새 컬럼으로 둔다
--
-- **`expel` 이 아니라 `promote` 다.** 이름은 expel 이 짝처럼 보이지만, 그건
-- 포커스가 어디 있든 컬럼 **맨 아래** 창을 뱉는다(니리 문서도 expel-window-
-- from-column 을 "the bottom window" 라고 적는다). 골라서 빼내는 건 promote 뿐
-- 이다. 좌표를 재서 확인했다 — docs/hyprland-binds.md 의 layoutmsg 표.
--
-- 컬럼 판별은 x 좌표다. 같은 컬럼의 창들은 x 가 정확히 같고 컬럼끼리는 다르다.
-- 띄운 창은 이 계산에서 빼야 아무 데나 걸쳐 있는 플로팅 하나가 판정을 뒤집지
-- 않는다.
--
-- 왕복이 완전하지는 않다. promote 로 나간 창은 맨 오른쪽 컬럼이 되므로 다시
-- 누르면 `no next column` 이다 — 가져올 다음 컬럼이 없으니 맞는 대답이다.
-- 되돌리려면 왼쪽 컬럼을 잡고 누르면 된다. 니리의 방향성도 같다.
hl.bind(mod .. " + CTRL + E", function()
    local act = hl.get_active_window()
    if not act or act.floating then return end
    local siblings = 0
    for _, w in ipairs(hl.get_workspace_windows(act.workspace)) do
        if not w.floating and w.at.x == act.at.x then siblings = siblings + 1 end
    end
    hl.dispatch(hl.dsp.layout(siblings > 1 and "promote" or "consume"))
end)

-- 마우스. 니리엔 없지만 하이프랜드에선 관용이고, 띄운 창을 다룰 때 편하다.
hl.bind(mod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- 스크린샷. 니리는 컴포지터가 직접 찍지만 하이프랜드는 아니라서 hyprshot 을
-- 쓴다(../default.nix 가 깐다). 저장 위치는 니리의 screenshot-path 와 맞췄다.
local shot = "hyprshot --silent --output-folder ~/Pictures/Screenshots -m "
hl.bind("Print", hl.dsp.exec_cmd(shot .. "region"))
hl.bind("CTRL + Print", hl.dsp.exec_cmd(shot .. "output"))
-- `-m window` 만 주면 hyprshot 이 창을 고르라고 기다린다. 니리의
-- screenshot-window 는 묻지 않고 지금 창을 찍으므로 active 를 덧붙인다.
hl.bind("ALT + Print", hl.dsp.exec_cmd(shot .. "window -m active"))

-- 미디어/밝기. locked=true 는 잠금 화면에서도 먹으라는 뜻이다(니리의
-- allow-when-locked), repeating=true 는 누르고 있으면 반복.
local mediakey = { locked = true, repeating = true }
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("dms ipc call audio increment 5"), mediakey)
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("dms ipc call audio decrement 5"), mediakey)
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("dms ipc call audio mute"), { locked = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("dms ipc call mic mute"), { locked = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("dms ipc call brightness increment 5"), mediakey)
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("dms ipc call brightness decrement 5"), mediakey)

-- 리싱 스크립트. exec_cmd 는 sh -c 를 거치므로 $HOME 이 풀린다.
-- 프로필 전환은 두 세션이 반씩 나눠 갖는다 — 니리 조각(profile.kdl)은 여기서
-- 아무 일도 안 하고, DMS 조각(색·투명도·둥글기)은 그대로 적용된다.
--
-- 이 묶음은 티어 규칙 밖이다. 리눅스 전용이고 방향키도 워크스페이스도 아니라
-- 어느 티어와도 실제로 부딪히지 않는다.
hl.bind(mod .. " + SHIFT + P", hl.dsp.exec_cmd("$HOME/nixos-config/apps/rice-switch --next"))
hl.bind(mod .. " + SHIFT + W", hl.dsp.exec_cmd("$HOME/nixos-config/apps/rice-wall"))
hl.bind(mod .. " + CTRL + W", hl.dsp.exec_cmd("$HOME/nixos-config/apps/rice-wall --pick"))
hl.bind(mod .. " + ALT + W", hl.dsp.exec_cmd("$HOME/nixos-config/apps/rice-wall --yazi"))

-- 축 하나에 키 하나씩 두는 건 셰이더 값을 고쳐 가며 맞출 때는 오히려 느리다.
-- 이건 DMS 런처를 RiceSwitcher 플러그인의 트리거(":")를 미리 친 채로 연다 —
-- 프로필·터미널·월페이퍼가 한 목록에 있고, 지금 걸린 것에 ✓ 가 붙는다.
-- 플러그인은 ../../dms/plugins/RiceSwitcher, 값은 apps/rice-menu 에서 온다.
-- 화면 셰이더는 이 목록에 값이 없다 — 고르는 자리가 별도 창이라(apps/rice-studio)
-- 여기에는 그 창을 여는 줄과 탈출구(off · 다음 것)만 있다.
hl.bind(mod .. " + SHIFT + R", hl.dsp.exec_cmd("dms ipc call spotlight toggleQuery ':'"))


-------------------
---- 화면 셰이더 ----
-------------------

-- 이 세션이 존재하는 이유. 렌더링이 끝난 화면 한 장에 프래그먼트 셰이더를 한 번
-- 더 거는 훅이고, 니리에는 이게 없다.
--
-- ── 목록과 순환은 여기 없다 ───────────────────────────────────────────────
-- 예전에는 이 파일이 셰이더 셋을 배열로 들고 직접 순환했다. 지금은
-- `apps/rice-crt --next` 를 부른다. 옮긴 이유는 셰이더가 열 몇 장이 된 것보다
-- **체인** 쪽이 크다 — 여러 장을 겹치면 하이프랜드에 걸 파일을 만들어 내야
-- 하는데(apps/rice-chain), 그건 lua 설정 안에서 할 일이 아니다. 게다가 순환
-- 목록을 두 곳에 두면 갈래를 하나 늘릴 때마다 둘을 같이 고쳐야 하고, 안 고친
-- 쪽이 조용히 낡는다.
--
-- 그래서 이 자리에 남은 것은 "무엇으로 시작할까" 하나다.
--
-- ── 셰이더에 딸려 오는 두 축 ──────────────────────────────────────────────
-- 하나로 보이지만 둘이고, 서로 다른 조건에 묶인다. 한동안 이 둘을 하나로 묶어
-- 두는 바람에 증상이 둘 다 남았다 — docs/postmortems/2026-08-04-hyprland-crt.md.
--
-- debug:damage_tracking — 프레임을 그릴 때 *어디를* 그리는가
--   기준은 `time` 이 아니라 **셰이더가 자기 픽셀 밖을 읽는가** 다. 이 CRT 들은
--   전부 읽는다: curve() 는 배럴 왜곡이라 가장자리에서 수십 px 어긋난 곳을,
--   gun() 은 색수차로 ±3 px 를, bloom() 은 5 px 반경에 16 탭을 읽는다. 바뀐
--   사각형만 다시 합성하면 그 바깥 이웃이 낡아서 움직이는 것 둘레에 잔상이 남고,
--   stripes() 의 fwidth() 는 사각형 경계에서 불연속이라 스캔라인 세기가 사각형
--   모양으로 갈린다. 그래서 셰이더가 걸리면 무조건 0 이다.
--
-- debug:vfr — 프레임을 *그릴지 말지*
--   VFR 이 켜져 있으면 데미지가 없을 때 프레임을 아예 안 그린다. time 을 쓰는
--   셰이더는 거기서 멈춰서, 마우스를 움직여야 험 바가 한 칸 흐른다. 그래서 이쪽은
--   흐르는지로 갈린다 — 정지 셰이더는 화면이 바뀔 때만 다시 그리면 충분하고(실측:
--   damage 0 + vfr 켬으로 잔상 없음), 끄면 정지 화면을 주사율대로 다시 그리는
--   순수한 낭비가 된다.
--
--   판정은 `time` 유니폼이 있는지가 아니라 **흐르는 것을 여는 손잡이가 0 이 아닌지**
--   다. crt.frag 은 그레인·험 바·클릭 파문을 전부 0 으로 내리면 그 자리에서 정지
--   셰이더가 되고, 그때는 VFR 을 켜 두는 것이 맞다. 그 손잡이가 어느 것인지는
--   셰이더가 `!motion` 으로 스스로 선언한다(apps/rice-chain --motion).
--
-- 배터리 비용은 damage_tracking 이 아니라 이 vfr 쪽에 붙어 있다.
--
-- 로그인 직후부터 걸린다(아래 exec_cmd). 끄려면 Mod+Shift+C 로 off 까지 돌리거나
-- `apps/rice-crt off`. 그때 두 축 모두 하이프랜드 기본값으로 돌아간다. 이 파일을
-- 저장할 때마다 다시 걸리므로, off 로 둔 채 여기를 고치면 도로 켜진다.
local rice_crt = os.getenv("HOME") .. "/nixos-config/apps/rice-crt"

-- 로그인 때 걸 것. 갈래/이름 하나여도 되고 체인 이름이어도 된다:
--   "crt/crt"  "water/still"  "chain/bad-signal"  "off"
-- 여기를 고치고 저장하면 그 자리에서 다시 걸린다.
local crt_start = "crt/crt"

-- hl.dsp.exec_cmd 가 아니라 hl.exec_cmd 다. 이름이 같아서 헷갈리는데 뜻이 다르다:
-- dsp 쪽은 **디스패처를 만들어 돌려주고**(그래서 hl.bind 의 인자로 쓴다), 이쪽은
-- 그 자리에서 실행하고 nil 을 돌려준다(share/hypr/stubs/hl.meta.lua). dsp 쪽을
-- 여기에 쓰면 아무 일도 안 일어나고, 증상은 "로그인하면 셰이더가 안 걸린다"다.
hl.exec_cmd(rice_crt .. " " .. crt_start)

-- 다음 것은 *지금 걸려 있는 것*에서 고른다. 여기에 카운터를 두면 밖에서 바꾼
-- 순간(런처의 Rice 플러그인) 둘이 어긋나고, 낡은 카운터로 고른 "다음"은 엉뚱한
-- 데로 뛴다. 걸려 있는 셰이더는 컴포지터가 이미 알고 있으니 그쪽이 유일한
-- 진실이고, rice-crt 가 그걸 되읽는다.
hl.bind(mod .. " + SHIFT + C", hl.dsp.exec_cmd(rice_crt .. " --next"))
-- 이 바인드가 안 먹으면 같은 일을 밖에서 할 수 있다. `hyprctl keyword` 는 못 쓴다 —
-- lua 설정에서는 파서가 통째로 거절한다("keyword can't work with non-legacy
-- parsers. Use eval."). 남는 길은 eval 뿐이고, 그걸 감싼 게 rice-crt 다:
--   apps/rice-crt off | crt/crt | water/still | chain/bad-signal | --next | --reload
--   apps/rice-crt water/still print/paper     즉석 체인
--   hyprctl eval 'hl.config({decoration={screen_shader=""}})'


-------------------
---- DMS 조각 ----
-------------------

-- 셸이 설정 GUI 와 matugen 으로 써 넣는 파일들. 색·커서·모니터·창 규칙이 여기서
-- 온다. 마지막에 부르므로 겹치는 값(gaps, rounding)은 DMS 쪽이 이긴다 — 레포
-- 값으로 되돌리고 싶으면 그 줄을 빼면 된다.
--
-- pcall 인 건 니리 include 의 `optional=true` 와 같은 뜻이다. 파일 하나가
-- 없다고 설정 전체가 죽으면 세션이 통째로 하이프랜드 기본값으로 떨어진다.
--
-- binds-user 는 DMS 설정 GUI 가 키를 추가할 때 쓰는 자리다(기본은 빈 파일).
-- 위에서 이미 잡은 키를 거기서 또 잡으면 둘 다 실행되니, 그럴 땐 그 파일에서
-- hl.unbind() 를 먼저 부른다.
for _, fragment in ipairs({ "colors", "cursor", "outputs", "windowrules", "layout", "binds-user" }) do
    pcall(require, "dms." .. fragment)
end


-------------------
---- 장식 조각 ----
-------------------

-- 투명도·흐리게·어둡게·그림자. apps/rice-decor 가 쓰는 생성물이고, 라이싱
-- 스튜디오의 "장식" 탭이 그 스크립트를 부른다.
--
-- DMS 조각 **뒤에** 오는 것이 요점이다. 지금은 겹치는 키가 없지만(그쪽은
-- gaps·rounding·border_size, 이쪽은 opacity·blur·shadow) 언젠가 겹치면 나중에
-- 부른 이쪽이 이긴다. 그건 잘못된 방향이라, rice-decor 의 표에서 DMS 가 가진
-- 키를 아예 뺐다 — 순서가 아니라 표가 안전장치다.
--
-- 파일이 없어도 세션은 뜬다. 아무 값도 안 바꾼 머신에는 이 파일이 아예 없다.
pcall(require, "decor")
