-- hyprland 설정 — 손으로 고치는 파일이다. 생성물이 아니다.
--
-- 살아있는 사본은 ~/.config/hypr/hyprland.lua 이고 평범한 쓰기 가능 파일이다.
-- 저장하면 하이프랜드가 바로 리로드하고, 문법이 깨진 편집은 에러만 찍고 직전
-- 설정이 계속 돈다. 그러니 저기서 굴리고, 레포 쪽은 시드 겸 백업으로 둔다
-- (../default.nix 의 활성화 스크립트가 파일이 *없을 때만* 복사한다).
--
-- ── 왜 .conf 가 아니라 .lua 인가 ────────────────────────────────────────────
-- 0.55 부터 hyprlang 이 deprecated 이고 설정은 Lua 다. 인터넷에 널린
-- hyprland.conf 예제는 그대로 안 붙는다 — `hyprconf2lua` 로 변환하거나 아래
-- 문법을 따라 쓴다. 값 이름 자체는 그대로라, 위키의 변수표는 여전히 유효하다.
--
-- ── 니리와의 관계 ──────────────────────────────────────────────────────────
-- 키 배치는 ../../niri/rice/config.kdl 에서 그대로 옮겼다. 두 세션을 오가며 쓸
-- 거라 근육기억이 갈리는 게 제일 큰 비용이기 때문이다. 다만 1:1 은 아니고, 다른
-- 곳마다 주석을 달아 뒀다.
--
-- ── 레이아웃은 이 파일에 없다 ──────────────────────────────────────────────
-- general.layout 과 그 레이아웃에만 뜻이 있는 키(컬럼 사이 이동·폭·합치기)는
-- ./layouts/<이름>.lua 가 한 벌씩 들고 있고, 어느 것을 읽을지는
-- ~/.config/rice/layout 한 줄이 정한다(아래 「배치」절). 기본은 scrolling —
-- 무한 띠 위에 컬럼이 쌓이는, 니리와 같은 모델이다. 갈아끼우는 것은
-- apps/rice/layout 이고 라이싱 스튜디오의 「배치」탭이 그걸 부른다.

-- 이 파일은 하이프랜드가 자동 생성한 게 아니다. 안 적으면 첫 실행에 "설정을
-- 만들어 줬다"는 안내가 뜬다.
hl.config({ autogenerated = false })


---------------
---- 입력 ----
---------------

-- 키 리맵(한/영, Caps 레이어)은 여기 없다. keyd 가 evdev 레벨에서 처리하므로
-- 컴포지터가 뭐든 똑같이 먹는다 — ../../keyboard.nix 참고.
hl.config({
    input = {
        kb_layout = "us",

        -- 클릭해야 포커스가 간다. 세 WM 모두 같게 뒀다(니리는
        -- focus-follows-mouse 줄을 뺐고, rift 는 focus_follows_mouse = false).
        --
        -- 호버 포커스와 키보드 타일러는 누가 주도권을 갖는지에 대해 서로 다른
        -- 답을 갖고 있다. 포인터는 마지막으로 놓아둔 자리에 그대로 있으면서도
        -- 포커스에 대한 권리를 계속 주장한다 — 키보드로 옮겨 간 창에 타이핑을
        -- 시작하면 첫 타가 커서가 얹혀 있던 엉뚱한 창으로 들어갈 수 있고,
        -- 배경 창 위에서 스크롤하면 포커스를 통째로 빼앗긴다.
        --
        -- 반대 방향(키보드로 포커스를 옮기면 커서가 따라오는 것)은 rift 쪽에서
        -- 켜 두었다. 하이프랜드에 같은 설정은 없다.
        follow_mouse = 0,

        touchpad = {
            natural_scroll = true,
            tap_to_click = true,
            disable_while_typing = true, -- 니리의 dwt
        },
    },
})

-- 휠 클릭을 누른 채 마우스를 움직이면 스크롤(libinput 의 on-button-down).
-- 누르고 움직이지 않은 채 떼면 휠 클릭은 그대로 나가되, 눌린 순간이 아니라 뗀
-- 순간에 나간다 — libinput 이 스크롤이냐 클릭이냐를 릴리즈까지 유보하기 때문
-- 이다. 그 대가로 미들 드래그(패닝)는 전부 스크롤로 먹혀서 사라진다.
--
-- input 전역이 아니라 장치별로 거는 이유: input.scroll_method 는 터치패드에도
-- 걸리는데 input.touchpad 에는 이를 되돌릴 scroll_method 가 없다(0.56 스텁의
-- HL.ConfigOpt.Input.Touchpad 참고). 이 파일이 노트북에 심기는 순간 두 손가락
-- 스크롤이 조용히 죽는다. 마우스를 바꾸면 이름도 바꿔야 하고, 이름은
-- `hyprctl devices` 의 mice 절에 있다.
--
-- scroll_button_lock 은 켜지 않는다. 켜면 클릭 한 번이 스크롤 모드 토글이 되어
-- 휠 클릭 자체가 없어진다 — 이 설정으로 지키려던 것이 그것이다.
hl.device({
    name = "compx-2.4g-receiver-mouse",
    scroll_method = "on_button_down",
    scroll_button = 274, -- BTN_MIDDLE
})

-- 세 손가락 가로 스와이프로 워크스페이스 전환. **트랙패드 전용이다** —
-- 손가락으로 화면을 쓸어도 이 줄은 안 탄다. 0.56 의 제스처 엔진은 통째로
-- 트랙패드 것이고(바이너리 심볼이 전부 `C*TrackpadGesture` 다), 터치스크린은
-- 아래 workspace_swipe_touch 라는 구형 경로로만 워크스페이스를 넘긴다.
hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })

-- 터치스크린. 터치 장치가 없는 머신에서는 통째로 무의미하고 에러도 안 난다.
hl.config({
    input = {
        touchdevice = {
            -- 디지타이저를 내장 패널에 못 박는다. 이 줄이 없으면 외장 모니터를
            -- 붙이는 순간 터치 좌표가 **전체 레이아웃**(내장+외장을 합친 넓이)에
            -- 매핑되어, 화면을 찍으면 가로로 눌린 엉뚱한 자리가 눌린다. 모니터
            -- 하나일 때는 증상이 없으므로 케이블을 꽂기 전까지 안 드러난다.
            output = "eDP-1",
        },

        -- 스타일러스도 같은 이유로 같은 패널에 못 박는다. 위키와 예전 이슈에는
        -- 태블릿 transform 이 없다고 적혀 있지만 0.56 에는 있다 —
        -- `hyprctl getoption input:tablet:transform` 이 답한다.
        tablet = {
            output = "eDP-1",
        },
    },

    gestures = {
        -- 손가락 가로 스와이프로 워크스페이스. 위 hl.gesture 와 별개의 경로이고,
        -- 터치스크린에서 워크스페이스를 넘기는 방법은 0.56 기준 이것뿐이다.
        workspace_swipe_touch = true,
    },
})

-- 태블릿 모드. 화면을 360도로 접으면 EC 가 SW_TABLET_MODE 를 세우고, 하이프랜드는
-- 그것을 스위치 장치로 본다 — `hyprctl devices` 의 Switches 절에 "Tablet Mode
-- Switch" 로 나온다. 그 이름이 곧 아래 키 문자열이므로, 다른 섀시에 심으면
-- 이름이 달라 조용히 안 걸린다(거기엔 접을 화면도 없다).
--
-- `tablet-mode` 자체는 갤럭시 크롬북의 touch.nix 가 깐다. 키보드 억제·터치패드·
-- 자동 회전·화면 키보드 네 가지를 같이 움직이고, 왜 libinput 에 맡기지 않는지는
-- 그 파일에 적혀 있다.
--
-- locked = true 는 잠금 화면에서도 걸리게 한다. 잠긴 채로 접는 것이 오히려
-- 흔한 동작이고, 그때 자판이 등 뒤에서 눌리는 것이 제일 곤란하다.
hl.bind("switch:on:Tablet Mode Switch",
    hl.dsp.exec_cmd("tablet-mode enter"), { locked = true })
hl.bind("switch:off:Tablet Mode Switch",
    hl.dsp.exec_cmd("tablet-mode leave"), { locked = true })


-------------------
---- 모양/배치 ----
-------------------

hl.config({
    general = {
        gaps_in = 4,
        gaps_out = 8,
        border_size = 2,
        -- layout 은 여기 없다. 레이아웃마다 키바인드가 같이 갈려야 해서 둘을
        -- 한 파일에 묶었다 — ./layouts/<이름>.lua (아래 「배치」절).
    },

    -- 투명도·흐리게·어둡게·그림자는 여기 없다. 손으로 정하는 값이 아니라 화면을
    -- 보면서 맞추는 값이라 apps/rice/decor 가 ~/.config/hypr/decor.lua 에 쓰고,
    -- 그 조각을 이 파일 맨 끝에서 부른다. 둥글기만 여기 남는데, 그것도 DMS 가
    -- 덮는다(맨 아래 조각 주석).
    decoration = {
        rounding = 12,
    },

    misc = {
        -- DMS 가 벽지를 깐다. 하이프랜드 기본 배경은 그 밑에서 한 번 번쩍일
        -- 뿐이라 꺼 둔다.
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        force_default_wallpaper = 0,

        -- 이미 떠 있는 앱을 다시 켰을 때 그 창으로 포커스가 간다. 기본값은 false.
        --
        -- 단일 인스턴스 앱(OnlyOffice 등)은 두 번째 실행이 기존 인스턴스에 넘기고
        -- 죽는다. 그때 그 인스턴스가 보내는 "나를 띄워 달라"(xdg-activation, X11
        -- 은 _NET_ACTIVE_WINDOW)를 false 면 하이프랜드가 버리고, 증상은 "켰는데
        -- 아무 일도 안 일어남"이 된다. 스크롤링 레이아웃에서 특히 나쁘다 — 창은
        -- 띠 위에 살아 있는데 화면 밖이라 살아 있다는 증거조차 없다. XWayland
        -- 창은 스스로 포커스를 못 가져오므로 더 그렇다.
        --
        -- 대가는 앱이 아무 때나 포커스를 뺏을 수 있다는 것이다. 거슬리는 창이
        -- 나오면 전역을 끄지 말고 그 창에만 windowrule 로 좁힌다.
        focus_on_activate = true,
    },
})

-- DMS 의 레이어(바, 스포트라이트, 알림)에는 애니메이션을 걸지 않는다. 셸이
-- 자기 안에서 이미 애니메이션을 하고 있어서 두 번 겹친다.
hl.layer_rule({ name = "dms-no-anim", match = { namespace = "^dms:.*" }, no_anim = true })
hl.layer_rule({ name = "quickshell-no-anim", match = { namespace = "^(quickshell)$" }, no_anim = true })


-------------------
---- 환경 변수 ----
-------------------

-- 여기서 세운 값은 *하이프랜드가 띄우는 자식 프로세스*에만 간다. DMS 는 uwsm 이
-- 만든 systemd 유닛으로 뜨므로 이 값들을 못 본다 — 셸까지 닿아야 하는 변수는
-- ~/.config/uwsm/env 나 NixOS 의 environment.sessionVariables 로 가야 한다.
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("QT_QPA_PLATFORM", "wayland")


-------------------
---- 키바인드 ----
-------------------

-- DMS 도 자기 기본 키바인드 묶음(dms/binds.lua)을 깔아 두지만 여기서는 안
-- 읽는다. **하이프랜드는 같은 키에 걸린 바인드를 위에서부터 전부 실행한다** —
-- 니리처럼 나중 것이 앞 것을 덮지 않는다. 그래서 겹치는 키(Mod+F, Mod+Q...)가
-- 토글을 두 번 때려 아무 일도 안 일어나는 꼴이 된다. 필요한 IPC 호출은 아래에
-- 직접 적었고, 셸이 만드는 치트시트(Mod+Shift+/)는 이 파일을 읽으므로 목록은
-- 그대로 나온다.
local mod = "SUPER"

-- 세 티어가 전부다. rift 와 니리도 같은 세 티어이고, macOS 만 mod 가 Alt 다
-- (Cmd 는 시스템이 가져간다). 전체 표는 docs/keymap.md.
--
--   Mod          간다, 연다
--   Mod + SHIFT  창을 데리고 간다
--   Mod + CTRL   모니터를 넘는다, WM 자신에게 말한다
--
-- 예전엔 이동이 Mod+CTRL 이었다. 그 자리를 SHIFT 로 옮긴 건 CTRL 티어를
-- 비우기 위해서다 — 모니터 이동을 넣을 자리가 없었다.

-- 프로그램
hl.bind(mod .. " + Return", hl.dsp.exec_cmd("ghostty"))
-- 셸이 안 뜬 상태(베타 업데이트, 잘못된 설정)에서도 터미널을 열 수 있는 길.
-- 니리 쪽과 같은 이유로 남겨 둔 폴백 런처다.
hl.bind(mod .. " + D", hl.dsp.exec_cmd("fuzzel"))

-- 화면 키보드(wvkbd). `osk` 는 갤럭시 크롬북의 touch.nix 가 깐다 — 터치스크린이
-- 없는 머신에서 이 키를 누르면 아무 일도 안 일어난다.
--
-- 이 바인드는 **노트북 자세용**이다. 화면을 접어 키보드가 등 뒤로 가면 이 키를
-- 누를 수가 없고, 그쪽은 아래 태블릿 모드 스위치가 맡는다. B 는 자판(Board).
hl.bind(mod .. " + B", hl.dsp.exec_cmd("osk toggle"))

-- DMS
hl.bind(mod .. " + space", hl.dsp.exec_cmd("dms ipc call spotlight toggle"))
hl.bind(mod .. " + V", hl.dsp.exec_cmd("dms ipc call clipboard toggle"))
hl.bind(mod .. " + N", hl.dsp.exec_cmd("dms ipc call notifications toggle"))
hl.bind(mod .. " + S", hl.dsp.exec_cmd("dms ipc call control-center toggle"))
hl.bind(mod .. " + Escape", hl.dsp.exec_cmd("dms ipc call powermenu toggle"))
-- 치트시트. 셸이 이 파일을 읽어서 만든다. H 는 IJKL 이 왼쪽을 J 로 가져가면서
-- 통째로 빈 자리가 됐고, Help 로 읽힌다. rift 에는 대응물이 없다 —
-- 그쪽 치트시트는 docs/keymap.md 다.
hl.bind(mod .. " + H", hl.dsp.exec_cmd("dms ipc call keybinds toggle hyprland"))
-- 오버뷰. 예전엔 Mod+O 였는데 그 자리는 이제 워크스페이스 앞으로 가기다.
-- rift 는 같은 키에서 macOS 미션 컨트롤을 연다.
hl.bind(mod .. " + E", hl.dsp.exec_cmd("dms ipc call hypr toggleOverview"))
--
-- 버린 것 둘:
--   Mod+L      잠금. IJKL 이 오른쪽을 L 로 가져갔다. 잠금은 Mod+Escape 의
--              파워메뉴에 있고, 거기엔 잘못 눌렀을 때 되돌릴 기회까지 있다.
--   Mod+comma  DMS 설정 GUI. 런처에서 이름으로 부르면 된다. rift 는 이 자리를
--              toggle_stack 으로 쓴다.
--
-- Mod+SHIFT+E 는 로그아웃(`uwsm stop`)이었다. Mod+SHIFT+F / Mod+SHIFT+space 와
-- 손 모양이 겹쳐서 오타 한 번이면 세션이 통째로 날아가는 자리라 뺐다. 다시 걸 일이
-- 있으면 **hl.dsp.exit() 이 아니라** `uwsm stop` 이다 — uwsm 세션에서 컴포지터를
-- 직접 죽이면 클라이언트 밑에서 바닥을 빼는 꼴이라 유닛들이 어중간하게 남는다.

-- 창
hl.bind(mod .. " + Q", hl.dsp.window.close())
hl.bind(mod .. " + F", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }))
hl.bind(mod .. " + SHIFT + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(mod .. " + SHIFT + space", hl.dsp.window.float({ action = "toggle" }))

------------------------------------------------------------------------
-- 티어 1 — Mod: 간다
------------------------------------------------------------------------
-- 방향은 IJKL, 화살표와 같은 역T자다:
--
--         I                 ↑
--    J    K    L        ←   ↓   →
--
-- hjkl 이 아니다. hjkl 은 한 줄에 늘어선 네 개일 뿐 모양이 없다 — vim 유산이지
-- 공간이 아니고, 창 관리는 공간 작업이다. 화살표는 어느 티어에서든 같은 동작에
-- 같이 걸려 있다. IJKL 이 흉내내는 대상이기도 하고, K 가 "위"에서 "아래"로
-- 뒤집힌 걸 손이 익히는 동안의 안전망이기도 하다.
--
-- 위아래(I/K)는 어느 레이아웃에서나 평범한 방향 포커스라 여기 있다. 좌우(J/L)는
-- 레이아웃이 정한다 — 스크롤링은 컬럼 사이를 감싸 도는 layout 메시지, dwindle 은
-- 트리 이웃이다. Mod+C · Mod+R · Mod+=/- 도 같은 이유로 그쪽에 있다
-- (./layouts/<이름>.lua, 아래 「배치」절).
hl.bind(mod .. " + I", hl.dsp.focus({ direction = "u" }))
hl.bind(mod .. " + K", hl.dsp.focus({ direction = "d" }))
hl.bind(mod .. " + up", hl.dsp.focus({ direction = "u" }))
hl.bind(mod .. " + down", hl.dsp.focus({ direction = "d" }))

-- 워크스페이스. U 가 뒤로, O 가 앞으로 — I 를 위에서 감싸는 두 자리다.
-- 예전엔 U/I 였는데 IJKL 이 I 를 가져갔다. 니리·rift 도 같은 두 키다.
hl.bind(mod .. " + U", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mod .. " + O", hl.dsp.focus({ workspace = "e+1" }))
-- 직전 워크스페이스. 검증함 (2026-08-06, 0.56.1) — 2↔5↔7 왕복까지 봤다.
--
-- 철자는 `previous` 여야 한다. `prev` 는 `ok` 를 돌려주면서 아무 일도 안 하고,
-- `previous_per_monitor` 는 `Bad workspace` 다.
--
-- 세션에 직전 워크스페이스가 아직 없을 때도 `Bad workspace` 가 나온다. 문법이
-- 틀렸을 때와 메시지가 같으니, 이 한 줄로 확인할 거면 워크스페이스를 한 번
-- 옮겼다 온 뒤에 해야 한다:
--
--   hyprctl dispatch 'hl.dsp.focus({ workspace = 5 })'
--   hyprctl dispatch 'hl.dsp.focus({ workspace = "previous" })'
hl.bind(mod .. " + Tab", hl.dsp.focus({ workspace = "previous" }))
for i = 1, 9 do
    hl.bind(mod .. " + " .. i, hl.dsp.focus({ workspace = i }))
end

------------------------------------------------------------------------
-- 티어 2 — Mod+SHIFT: 창을 데리고 간다
------------------------------------------------------------------------
-- 규칙 하나가 네 묶음에 그대로 걸린다: 방향, 워크스페이스 앞뒤, 워크스페이스
-- 번호, 그리고 큰 형제가 있는 창 상태 두 개(위의 F/space).
-- 좌우(SHIFT+J/L)는 티어 1 과 같은 이유로 레이아웃 파일에 있다 — 스크롤링은
-- 컬럼째 맞바꾸고(swapcol), dwindle 은 트리에서 옮겨 심는다(window.move).
hl.bind(mod .. " + SHIFT + I", hl.dsp.window.move({ direction = "u" }))
hl.bind(mod .. " + SHIFT + K", hl.dsp.window.move({ direction = "d" }))
hl.bind(mod .. " + SHIFT + up", hl.dsp.window.move({ direction = "u" }))
hl.bind(mod .. " + SHIFT + down", hl.dsp.window.move({ direction = "d" }))

hl.bind(mod .. " + SHIFT + U", hl.dsp.window.move({ workspace = "e-1" }))
hl.bind(mod .. " + SHIFT + O", hl.dsp.window.move({ workspace = "e+1" }))
-- 창을 워크스페이스 N 으로. rift 에만 있던 것이고, 여기 자리는 비어 있었다.
for i = 1, 9 do
    hl.bind(mod .. " + SHIFT + " .. i, hl.dsp.window.move({ workspace = i }))
end

------------------------------------------------------------------------
-- 티어 3 — Mod+CTRL: 모니터를 넘는다, WM 에게 말한다
------------------------------------------------------------------------
-- 검증함 (2026-08-06, 0.56.1, eDP-1 + DP-1 실기). `monitor` 는 방향 약자
-- l/r/u/d 와 full word(left/right/up/down)를 받고, 창이 실제로 넘어간다.
-- 이름·id·`current`·`+1`/`-1` 도 같이 받는다.
--
-- 옆에 모니터가 없는 방향은 `Invalid monitor / monitor doesn't exist` 다. 이게
-- 문법 오류처럼 보이는 게 함정이다 — 모니터가 하나뿐이면 네 방향이 전부 저
-- 메시지를 돌려주고, **겹쳐 배치된 모니터도 마찬가지다.** 헤드리스 출력을
-- 만들어 확인할 거면 위치부터 봐야 한다. `hyprctl output create headless` 는
-- 기존 모니터 안쪽에 얹히는 수가 있고, 그 배치에서는 어느 방향으로도 "옆"이
-- 아니다. `hyprctl keyword` 로는 못 옮긴다(lua 설정에서는 `eval` 뿐).
hl.bind(mod .. " + CTRL + J", hl.dsp.window.move({ monitor = "l" }))
hl.bind(mod .. " + CTRL + L", hl.dsp.window.move({ monitor = "r" }))
hl.bind(mod .. " + CTRL + I", hl.dsp.window.move({ monitor = "u" }))
hl.bind(mod .. " + CTRL + K", hl.dsp.window.move({ monitor = "d" }))
hl.bind(mod .. " + CTRL + left", hl.dsp.window.move({ monitor = "l" }))
hl.bind(mod .. " + CTRL + right", hl.dsp.window.move({ monitor = "r" }))
hl.bind(mod .. " + CTRL + up", hl.dsp.window.move({ monitor = "u" }))
hl.bind(mod .. " + CTRL + down", hl.dsp.window.move({ monitor = "d" }))

-- 이웃과 합치기 / 떼기(Mod+Ctrl+E)는 레이아웃 파일에 있다. 세 WM 에서 같은 키가
-- 같은 일을 하지만 하이프랜드에는 그 하나짜리 액션이 없고, 무엇이 "이웃"인지가
-- 레이아웃마다 다르다 — 스크롤링은 컬럼(consume/promote), dwindle 은 그룹이다.

-- 마우스. 니리엔 없지만 하이프랜드에선 관용이고, 띄운 창을 다룰 때 편하다.
hl.bind(mod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- 스크린샷. 니리는 컴포지터가 직접 찍지만 하이프랜드는 아니라서 hyprshot 을
-- 쓴다(../default.nix 가 깐다). 저장 위치는 니리의 screenshot-path 와 맞췄다.
local shot = "hyprshot --silent --output-folder ~/Pictures/Screenshots -m "
hl.bind("Print", hl.dsp.exec_cmd(shot .. "region"))
hl.bind("CTRL + Print", hl.dsp.exec_cmd(shot .. "output"))
-- `-m window` 만 주면 hyprshot 이 창을 고르라고 기다린다. 니리의
-- screenshot-window 는 묻지 않고 지금 창을 찍으므로 active 를 덧붙인다.
hl.bind("ALT + Print", hl.dsp.exec_cmd(shot .. "window -m active"))

-- 미디어/밝기. locked=true 는 잠금 화면에서도 먹으라는 뜻이다(니리의
-- allow-when-locked), repeating=true 는 누르고 있으면 반복.
local mediakey = { locked = true, repeating = true }
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("dms ipc call audio increment 5"), mediakey)
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("dms ipc call audio decrement 5"), mediakey)
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("dms ipc call audio mute"), { locked = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("dms ipc call mic mute"), { locked = true })
-- 밝기만 인자가 둘이다: `increment(step, device)`. 오디오 쪽(`increment(step)`)을
-- 보고 하나만 넘기면 DMS 가 "Too few arguments provided" 로 조용히 거절하고,
-- 화면에는 아무 일도 안 일어난다 — 키가 안 먹는 게 아니라 호출이 틀린 것이다.
-- 빈 문자열은 "기본 장치"라는 뜻이고, 그게 노트북 백라이트든 DDC 로 잡힌 외장
-- 모니터든 알아서 간다(evo-t1 에서는 ddc:i2c-10 = 40LGD5K 로 갔다).
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd('dms ipc call brightness increment 5 ""'), mediakey)
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd('dms ipc call brightness decrement 5 ""'), mediakey)

-- 리싱 스크립트. exec_cmd 는 sh -c 를 거치므로 $HOME 이 풀린다.
-- 프로필 전환은 두 세션이 반씩 나눠 갖는다 — 니리 조각(profile.kdl)은 여기서
-- 아무 일도 안 하고, DMS 조각(색·투명도·둥글기)은 그대로 적용된다.
--
-- 이 묶음은 티어 규칙 밖이다. 리눅스 전용이고 방향키도 워크스페이스도 아니라
-- 어느 티어와도 실제로 부딪히지 않는다.
-- 경로를 $HOME/nixos-config 로 박아 두지 않는 건 체크아웃을 딴 데 둘 수 있어서다.
-- exec 는 sh 를 거치므로 ${RICE_REPO:-…} 가 그대로 먹는다. 빗나가면 키가 조용히
-- 아무 일도 안 한다 — 하이프랜드는 exec 실패를 알려 주지 않는다. apps/doctor 가
-- 체크아웃 위치를 짚어 주는 이유가 이것이다.
hl.bind(mod .. " + SHIFT + P", hl.dsp.exec_cmd("${RICE_REPO:-$HOME/nixos-config}/apps/rice/switch --next"))
hl.bind(mod .. " + SHIFT + W", hl.dsp.exec_cmd("${RICE_REPO:-$HOME/nixos-config}/apps/rice/wall"))
hl.bind(mod .. " + CTRL + W", hl.dsp.exec_cmd("${RICE_REPO:-$HOME/nixos-config}/apps/rice/wall --pick"))
hl.bind(mod .. " + ALT + W", hl.dsp.exec_cmd("${RICE_REPO:-$HOME/nixos-config}/apps/rice/wall --yazi"))

-- 축 하나에 키 하나씩 두는 건 셰이더 값을 고쳐 가며 맞출 때는 오히려 느리다.
-- 이건 DMS 런처를 RiceSwitcher 플러그인의 트리거(":")를 미리 친 채로 연다 —
-- 프로필·터미널·월페이퍼가 한 목록에 있고, 지금 걸린 것에 ✓ 가 붙는다.
-- 플러그인은 ../../dms/plugins/RiceSwitcher, 값은 apps/rice/menu 에서 온다.
-- 화면 셰이더는 이 목록에 값이 없다 — 고르는 자리가 별도 창이라(apps/rice/studio)
-- 여기에는 그 창을 여는 줄과 탈출구(off · 다음 것)만 있다.
hl.bind(mod .. " + SHIFT + R", hl.dsp.exec_cmd("dms ipc call spotlight toggleQuery ':'"))


-------------------
---- 배치 ----
-------------------

-- general.layout 과 그 레이아웃에만 뜻이 있는 키들. ~/.config/hypr/layouts/
-- <이름>.lua 가 한 벌씩이고, 어느 것인지는 ~/.config/rice/layout 한 줄이 정한다.
-- 파일이 없으면 scrolling 이다 — 레포의 기본값이고, 레포에 둘 다 있다.
--
-- ── 왜 이 파일 안의 블록이 아니라 파일 하나씩인가 ───────────────────────
-- 레이아웃은 값 하나(general.layout)가 아니다. 컬럼 사이 이동·폭·합치기 키는
-- 레이아웃마다 **다른 디스패처**라, 값만 바꾸면 그 키들이 `Unknown layoutmsg`
-- 로 조용히 죽는다. 둘을 한 파일에 묶어 두면 그 어긋남이 생길 자리가 없다.
--
-- ── require 가 아니라 dofile 인 이유 ─────────────────────────────────────
-- decor.lua 와 같다. require 된 파일은 하이프랜드가 감시해서 저장할 때마다 설정
-- 전체가 리로드되고, 리로드는 걸어 둔 화면 셰이더까지 지운다. dofile 로 읽은
-- 파일은 감시 목록에 안 들어간다. 라이브 반영은 apps/rice/layout 이 eval 로
-- 한다 — 옛 파일이 걸었던 키를 풀고 새 파일을 돌리므로 리로드가 필요 없다.
-- 그러니 레이아웃 파일을 손으로 고쳤으면 `apps/rice/layout --reload`.
--
-- ── 실패하면 scrolling 으로 떨어진다 ─────────────────────────────────────
-- pcall 로 삼키고 끝내면 컬럼 키가 전부 죽은 세션이 소리 없이 뜬다. 문법이
-- 깨진 파일을 골라 뒀어도 기본 레이아웃의 키는 살아 있어야 고칠 수 있다.
do
    local home = os.getenv("HOME")
    local name = "scrolling"
    local f = io.open(home .. "/.config/rice/layout")
    if f then
        name = f:read("l") or name
        f:close()
    end
    local ok, err = pcall(dofile, home .. "/.config/hypr/layouts/" .. name .. ".lua")
    if not ok then
        print("rice: layouts/" .. name .. ".lua 를 못 돌렸다 — " .. tostring(err) .. " — scrolling 으로 간다")
        if name ~= "scrolling" then
            dofile(home .. "/.config/hypr/layouts/scrolling.lua")
        end
    end
end


-------------------
---- 화면 셰이더 ----
-------------------

-- 이 세션이 존재하는 이유. 렌더링이 끝난 화면 한 장에 프래그먼트 셰이더를 한 번
-- 더 거는 훅이고, 니리에는 이게 없다.
--
-- ── 목록과 순환은 여기 없다 ───────────────────────────────────────────────
-- 예전에는 이 파일이 셰이더 셋을 배열로 들고 직접 순환했다. 지금은
-- `apps/rice/crt --next` 를 부른다. 옮긴 이유는 셰이더가 열 몇 장이 된 것보다
-- **체인** 쪽이 크다 — 여러 장을 겹치면 하이프랜드에 걸 파일을 만들어 내야
-- 하는데(apps/rice/chain), 그건 lua 설정 안에서 할 일이 아니다. 게다가 순환
-- 목록을 두 곳에 두면 갈래를 하나 늘릴 때마다 둘을 같이 고쳐야 하고, 안 고친
-- 쪽이 조용히 낡는다.
--
-- 그래서 이 자리에 남은 것은 "무엇으로 시작할까" 하나다.
--
-- ── 셰이더에 딸려 오는 두 축 ──────────────────────────────────────────────
-- 하나로 보이지만 둘이고, 서로 다른 조건에 묶인다. 한동안 이 둘을 하나로 묶어
-- 두는 바람에 증상이 둘 다 남았다 — docs/postmortems/2026-08-04-hyprland-crt.md.
--
-- debug:damage_tracking — 프레임을 그릴 때 *어디를* 그리는가
--   기준은 `time` 이 아니라 **셰이더가 자기 픽셀 밖을 읽는가** 다. 이 CRT 들은
--   전부 읽는다: curve() 는 배럴 왜곡이라 가장자리에서 수십 px 어긋난 곳을,
--   gun() 은 색수차로 ±3 px 를, bloom() 은 5 px 반경에 16 탭을 읽는다. 바뀐
--   사각형만 다시 합성하면 그 바깥 이웃이 낡아서 움직이는 것 둘레에 잔상이 남고,
--   stripes() 의 fwidth() 는 사각형 경계에서 불연속이라 스캔라인 세기가 사각형
--   모양으로 갈린다. 그래서 셰이더가 걸리면 무조건 0 이다.
--
-- debug:vfr — 프레임을 *그릴지 말지*
--   VFR 이 켜져 있으면 데미지가 없을 때 프레임을 아예 안 그린다. time 을 쓰는
--   셰이더는 거기서 멈춰서, 마우스를 움직여야 험 바가 한 칸 흐른다. 그래서 이쪽은
--   흐르는지로 갈린다 — 정지 셰이더는 화면이 바뀔 때만 다시 그리면 충분하고(실측:
--   damage 0 + vfr 켬으로 잔상 없음), 끄면 정지 화면을 주사율대로 다시 그리는
--   순수한 낭비가 된다.
--
--   판정은 `time` 유니폼이 있는지가 아니라 **흐르는 것을 여는 손잡이가 0 이 아닌지**
--   다. crt.frag 은 그레인·험 바·클릭 파문을 전부 0 으로 내리면 그 자리에서 정지
--   셰이더가 되고, 그때는 VFR 을 켜 두는 것이 맞다. 그 손잡이가 어느 것인지는
--   셰이더가 `!motion` 으로 스스로 선언한다(apps/rice/chain --motion).
--
-- 배터리 비용은 damage_tracking 이 아니라 이 vfr 쪽에 붙어 있다.
--
-- ── 이 줄은 리로드마다 다시 돈다 ──────────────────────────────────────────
-- 하이프랜드는 이 파일과 require 된 조각이 바뀔 때마다 설정을 통째로 다시
-- 읽는데, 그때 screen_shader 는 비워진다 — 리로드 평가 시점에는 hl.get_config
-- 도 빈 값을 준다(실측 2026-08-12). DMS 는 테마·간격이 바뀔 때마다 dms/ 조각을
-- 다시 쓰므로, **프로필 전환마다** 리로드가 일어난다. 여기서 이름 하나를 그대로
-- 걸면 그때마다 골라 둔 셰이더가 그 이름으로 되돌아간다(실제로 그랬다).
--
-- 그래서 --boot 다: 마지막으로 걸었던 것(~/.config/rice/shader, rice-crt 가
-- 걸 때마다 적는다)을 도로 걸고, 그게 없을 때만 아래 기본값이다. off 로 꺼
-- 뒀으면 off 로 남는다.
local rice_crt = (os.getenv("RICE_REPO") or (os.getenv("HOME") .. "/nixos-config"))
                 .. "/apps/rice/crt"

-- 첫 로그인(아직 아무것도 안 걸어 본 머신)에 걸 것. 갈래/이름 하나여도 되고
-- 체인 이름이어도 된다:
--   "crt/crt"  "water/still"  "chain/bad-signal"  "off"
-- 한 번이라도 스위처로 골랐으면 그쪽이 이긴다 — 여기를 고쳐서 바꾸는 게
-- 아니라 apps/rice/crt 로 걸면 된다.
local crt_start = "crt/crt"

-- hl.dsp.exec_cmd 가 아니라 hl.exec_cmd 다. 이름이 같아서 헷갈리는데 뜻이 다르다:
-- dsp 쪽은 **디스패처를 만들어 돌려주고**(그래서 hl.bind 의 인자로 쓴다), 이쪽은
-- 그 자리에서 실행하고 nil 을 돌려준다(share/hypr/stubs/hl.meta.lua). dsp 쪽을
-- 여기에 쓰면 아무 일도 안 일어나고, 증상은 "로그인하면 셰이더가 안 걸린다"다.
hl.exec_cmd(rice_crt .. " --boot " .. crt_start)

-- 다음 것은 *지금 걸려 있는 것*에서 고른다. 여기에 카운터를 두면 밖에서 바꾼
-- 순간(런처의 Rice 플러그인) 둘이 어긋나고, 낡은 카운터로 고른 "다음"은 엉뚱한
-- 데로 뛴다. 걸려 있는 셰이더는 컴포지터가 이미 알고 있으니 그쪽이 유일한
-- 진실이고, rice-crt 가 그걸 되읽는다.
hl.bind(mod .. " + SHIFT + C", hl.dsp.exec_cmd(rice_crt .. " --next"))
-- 이 바인드가 안 먹으면 같은 일을 밖에서 할 수 있다. `hyprctl keyword` 는 못 쓴다 —
-- lua 설정에서는 파서가 통째로 거절한다("keyword can't work with non-legacy
-- parsers. Use eval."). 남는 길은 eval 뿐이고, 그걸 감싼 게 rice-crt 다:
--   apps/rice/crt off | crt/crt | water/still | chain/bad-signal | --next | --reload
--   apps/rice/crt water/still print/paper     즉석 체인
--   hyprctl eval 'hl.config({decoration={screen_shader=""}})'


-------------------
---- DMS 조각 ----
-------------------

-- 셸이 설정 GUI 와 matugen 으로 써 넣는 파일들. 색·커서·모니터·창 규칙이 여기서
-- 온다. 마지막에 부르므로 겹치는 값(gaps, rounding)은 DMS 쪽이 이긴다 — 레포
-- 값으로 되돌리고 싶으면 그 줄을 빼면 된다.
--
-- pcall 인 건 니리 include 의 `optional=true` 와 같은 뜻이다. 파일 하나가
-- 없다고 설정 전체가 죽으면 세션이 통째로 하이프랜드 기본값으로 떨어진다.
--
-- binds-user 는 DMS 설정 GUI 가 키를 추가할 때 쓰는 자리다(기본은 빈 파일).
-- 위에서 이미 잡은 키를 거기서 또 잡으면 둘 다 실행되니, 그럴 땐 그 파일에서
-- hl.unbind() 를 먼저 부른다.
--
-- ── 이름을 리터럴로 적어 두는 이유 ────────────────────────────────────────
-- DMS 의 커서 테마 설정(Modules/Settings/ThemeColorsTab.qml)은 이 파일이 조각을
-- 읽고 있는지를 **문자열 검색**으로 판정한다:
--
--   grepPattern: "dms.cursor"   includeLine: require("dms.cursor")
--
-- 못 찾으면 파일 끝에 그 줄을 덧붙인다. 이름을 런타임에 조립하면(`"dms." ..
-- fragment`) 리터럴이 파일에 안 나타나므로, 이미 읽고 있는 조각을 한 번 더
-- require 하는 줄이 붙고 그게 apps/rice/save 를 타고 레포까지 간다. 니리 쪽
-- (../../niri/rice/config.kdl)은 `include "dms/cursor.kdl"` 이 그대로 적혀 있어
-- 같은 일이 없다.
--
-- 목록을 펴 두면 리터럴이 생기고, 덤으로 무엇을 읽는지가 바로 보인다.
for _, fragment in ipairs({ "dms.colors", "dms.cursor", "dms.outputs", "dms.windowrules", "dms.layout", "dms.binds-user" }) do
    pcall(require, fragment)
end


-------------------
---- 장식 조각 ----
-------------------

-- 투명도·흐리게·어둡게·그림자. apps/rice/decor 가 쓰는 생성물이고, 라이싱
-- 스튜디오의 "장식" 탭이 그 스크립트를 부른다.
--
-- DMS 조각 **뒤에** 오는 것이 요점이다. 지금은 겹치는 키가 없지만(그쪽은
-- gaps·rounding·border_size, 이쪽은 opacity·blur·shadow) 언젠가 겹치면 나중에
-- 부른 이쪽이 이긴다. 그건 잘못된 방향이라, rice-decor 의 표에서 DMS 가 가진
-- 키를 아예 뺐다 — 순서가 아니라 표가 안전장치다.
--
-- require 가 아니라 dofile 인 것도 요점이다. require 된 파일은 하이프랜드가
-- 감시해서, 스튜디오 슬라이더를 움직일 때마다(rice-decor 가 이 파일을 통째로
-- 다시 쓴다) 설정 전체가 리로드된다. dofile 로 읽은 파일은 감시 목록에 안
-- 들어간다(실측 2026-08-12 — 설정 디렉터리 안이어도). 값의 라이브 반영은
-- rice-decor 의 eval 이 이미 하므로, 이 줄은 다음 세션과 리로드를 위한 것이다.
--
-- 파일이 없어도 세션은 뜬다. 아무 값도 안 바꾼 머신에는 이 파일이 아예 없다.
pcall(dofile, os.getenv("HOME") .. "/.config/hypr/decor.lua")
